FROM python:3-alpine3.18

ENV DIR=/srv/docker/textextraction

RUN mkdir file_loader

WORKDIR ${DIR}/file_loader

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

VOLUME [ "${DIR}/file_loader" ]

ENTRYPOINT [ "python3" , "main.py" ]
