version: '3.7'

services:
  test_container:
    build: 
      context: .
      dockerfile: Dockerfile_test_image

    container_name: Project_tester

    command: python -m unittest discover -s src -p 'test_*.py'

    volumes:
      - ./.testEnv:/project
