FROM python:3-alpine3.18

ENV DIR=/srv/docker/textextraction

RUN mkdir file_loader

WORKDIR ${DIR}/file_loader

COPY . ${DIR}/file_loader

RUN pip install -r requirements.txt

RUN pip install --editable .

ENTRYPOINT [ "python3" , "src/file_loader/main.py" ]
