FROM python:3-alpine3.18

ENV DIR=/srv/docker/textextraction

RUN mkdir text_extraction

RUN apk add poppler-utils

RUN apk add tesseract-ocr

ENV TESSDATA_PREFIX /usr/share/tesseract-ocr/4.00/tessdata

WORKDIR ${DIR}/text_extraction

COPY . ${DIR}/text_extraction

RUN pip install -r requirements.txt

RUN pip install --editable .

ENTRYPOINT [ "python3" , "-u", "src/text_extraction/main.py" ]
