version: '3.7'

services:
  spell_checking:
    image: ghcr.io/knox-aau/preprocessessing_text-extraction/spell_checking:latest

    container_name: spell_checking

    restart: on-failure

    volumes:
      - /srv/data/textextraction/watched:/watched

  file_loader:
    image: ghcr.io/knox-aau/preprocessessing_text-extraction/file_loader:latest

    container_name: file_loader

    restart: on-failure

    volumes:
      - /srv/data/textextraction/${file_loader_src}:/${file_loader_dist}
  
  # text_extraction:
  #   image: ghcr.io/knox-aau/preprocessessing_text-extraction/text_extraction:latest

  #   container_name: text_extraction

  #   restart: on-failure

  #   volumes:
  #     - /srv/data/textextraction/${text_extraction_src}:/${text_extraction_dist}