on: 
  pull_request:
    branches:
      - main

jobs:
  linter:
    name: PyLint check
    runs-on: ubuntu-latest
    steps: 
      - name: linter checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: pip install -r requirements.txt
      - run: pylint **/*.py


  testing:
    name: UnitTest
    runs-on: ubuntu-latest
    steps:
      - name: checkout and testing
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - run: "python3 -m unittest discover -s src/tests"
